# FIX: ld: unknown option: --as-needed
[target.arm-unknown-linux-musleabi]
linker = "arm-linux-musleabi-ld"

[target.arm-unknown-linux-musleabihf]
linker = "arm-linux-musleabihf-ld"

[target.armv7-unknown-linux-musleabi]
linker = "arm-linux-musleabi-ld"

[target.armv7-unknown-linux-musleabihf]
# linker = "arm-linux-gnueabihf-ld"
linker = "arm-linux-musleabihf-ld"

# [target.x86_64-linux-musleabi]
# linker = "x86_64-linux-gnueabihf-ld"
